module.exports = [
  {
    name: "truckload.io (Web)",
    nameLinked: true,
    subtitle: "Packing Visualization",
    slug: "truckload-io-web",
    type: "Web App",
    tags: ["React", "GCP", "Python"],
    description: "3D truckload packing visualization and load optimization",
    link: "https://truckload.io",
    linkLabel: "Visit Site",
    images: ["/apps/truckload-io-web/imgs/01.png", "/apps/truckload-io-web/imgs/02.png", "/apps/truckload-io-web/imgs/03.png"],
  },
  {
    name: "truckload.io (iOS)",
    nameLinked: true,
    subtitle: "Packing Visualization",
    slug: "truckload-io-ios",
    type: "iOS App",
    tags: ["React Native", "EAS", "Expo", "TSX"],
    description: "3D truckload packing visualization and load optimization for iPhone",
    link: "https://apps.apple.com/us/app/truckload-io/id6760942212",
    linkLabel: "View in App Store",
    images: ["/apps/truckload-io-ios/imgs/01.png", "/apps/truckload-io-ios/imgs/02.png", "/apps/truckload-io-ios/imgs/03.png"],
  },
  {
    name: "Buy Later",
    nameLinked: true,
    subtitle: "30 Day Countdown",
    slug: "buy-later-ios",
    type: "iOS App",
    tags: ["React Native", "Expo", "JSX"],
    description: "Delay impulse buys with a fixed 30 day cooldown",
    link: "https://apps.apple.com/us/app/buy-later-30-day-countdown/id6745124585",
    linkLabel: "View in App Store",
    images: ["/apps/buy-later-ios/imgs/01.png", "/apps/buy-later-ios/imgs/02.png", "/apps/buy-later-ios/imgs/03.png"],
  },
  {
    name: "K1 Freight",
    nameLinked: true,
    subtitle: "Transportation & Logistics",
    slug: "k1freight-web",
    type: "Website",
    tags: ["Next.js", "GCP", "HTML"],
    description: "Landing for the K1 Freight website including dynamic heatmaps and live counters",
    link: "https://k1freight.com",
    linkLabel: "Visit Site",
    imageLayout: "landscape",
    images: ["/apps/k1freight-web/imgs/landing.png", "/apps/k1freight-web/imgs/services.png", "/apps/k1freight-web/imgs/heatmap.png"],
  },
];
