module.exports = [
	{
		name: "Buy Later",
		nameLinked: true,
		subtitle: "30 Day Countdown",
		slug: "buy-later",
		type: "iOS App",
		tags: ["React Native", "Expo", "JSX"],
		description: "Delay impulse buys with a fixed 30 day cooldown",
		link: "https://apps.apple.com/us/app/buy-later-30-day-countdown/id6745124585",
		linkLabel: "View in App Store",
		images: [
			"/assets/buy-later/01.png",
			"/assets/buy-later/02.png",
			"/assets/buy-later/04.png",
		],
	},
	{
		name: "truckload.io",
		nameLinked: true,
		subtitle: "Load Planner",
		slug: "truckload-io",
		type: "iOS App",
		tags: ["React Native", "Expo", "JSX"],
		description: "3D truckload packing visualization and load optimization for iPhone",
		link: "https://apps.apple.com/us/app/truckload-io/",
		linkLabel: "View in App Store",
		images: [
			"/apps/truckload-io/imgs/apple/01.png",
			"/apps/truckload-io/imgs/apple/02.png",
			"/apps/truckload-io/imgs/apple/03.png",
		],
	},
	{
		name: "truckload.io",
		subtitle: "Packing Visualization",
		slug: "truckloadio",
		type: "Web App",
		tags: ["React", "GCP", "Python"],
		description: "3D truckload packing visualization and load optimization",
		link: "https://truckload.io",
		linkLabel: "Visit Site",
		images: [
			"/assets/truckloadio/01.png",
			"/assets/truckloadio/02.png",
			"/assets/truckloadio/03.png",
		],
	},
	{
		name: "K1 Freight",
		nameLinked: true,
		subtitle: "Transportation & Logistics",
		slug: "k1freight",
		type: "Website",
		tags: ["Next.js", "GCP", "HTML"],
		description: "Landing for the K1 Freight website including dynamic heatmaps and live counters",
		link: "https://k1freight.com",
		linkLabel: "Visit Site",
		imageLayout: "landscape",
		images: [
			"/assets/k1freight-website/landing.png",
			"/assets/k1freight-website/services.png",
			"/assets/k1freight-website/heatmap.png",
		],
	},
];
