module.exports = [
  {
    name: "truckload.io (web)",
    nameLinked: true,
    subtitle: "Packing Visualization",
    slug: "truckload-io-web",
    type: "Web App",
    tags: ["React", "TypeScript", "Vite", "Tailwind", "Three.js", "Zustand", "Python", "FastAPI", "Docker", "GCP"],
    description: "3D truckload packing visualization and load optimization",
    link: "https://truckload.io",
    linkLabel: "Visit Site",
    images: ["/apps/truckload-io-web/imgs/01.png", "/apps/truckload-io-web/imgs/02.png", "/apps/truckload-io-web/imgs/03.png"],
  },
  {
    name: "truckload.io (iOS)",
    nameLinked: true,
    subtitle: "Packing Visualization",
    slug: "truckload-io-ios",
    type: "iOS App",
    tags: ["React Native", "Expo", "Expo Router", "TypeScript", "Zustand", "EAS"],
    description: "3D truckload packing visualization and load optimization for iPhone",
    link: "https://apps.apple.com/us/app/truckload-io/id6760942212",
    linkLabel: "View in App Store",
    images: ["/apps/truckload-io-ios/imgs/01.png", "/apps/truckload-io-ios/imgs/02.png", "/apps/truckload-io-ios/imgs/03.png"],
  },
  {
    name: "Dynamic Mathematics",
    nameLinked: true,
    subtitle: "Adaptive Math Practice",
    slug: "dynamath-ios",
    type: "iOS App",
    tags: ["React Native", "Expo", "TypeScript", "React Navigation", "Swift", "SwiftMath", "SQLite", "Skia", "Zustand", "Firebase", "EAS"],
    description: "Adaptive math diagnostic that maps your skills and points you to what to practice next.",
    link: "https://apps.apple.com/us/app/dynamic-mathematics/id6762821417",
    linkLabel: "View in App Store",
    images: ["/apps/dynamath-ios/imgs/01.png", "/apps/dynamath-ios/imgs/02.png", "/apps/dynamath-ios/imgs/03.png"],
  },
  {
    name: "Buy Later",
    nameLinked: true,
    subtitle: "30 Day Countdown",
    slug: "buy-later-ios",
    type: "iOS App",
    tags: ["React Native", "Expo", "Expo Router", "JavaScript", "EAS"],
    description: "Improve spending habits by adding a cooldown period between wanting to buy something and actually buying it.",
    link: "https://apps.apple.com/us/app/buy-later-30-day-countdown/id6745124585",
    linkLabel: "View in App Store",
    images: ["/apps/buy-later-ios/imgs/01.png", "/apps/buy-later-ios/imgs/02.png", "/apps/buy-later-ios/imgs/03.png"],
  },
  {
    name: "Do Later",
    nameLinked: true,
    subtitle: "A Minimalist To-Do List",
    slug: "do-later-ios",
    type: "iOS App",
    tags: ["React Native", "Expo", "Expo Router", "TypeScript", "Reanimated", "EAS"],
    description: "A minimalist to-do list with recurring task generators.",
    link: "",
    linkLabel: "Coming Soon",
    images: ["/apps/do-later-ios/imgs/01.png", "/apps/do-later-ios/imgs/02.png", "/apps/do-later-ios/imgs/03.png"],
  },
  {
    name: "K1 Freight",
    nameLinked: true,
    subtitle: "Transportation & Logistics",
    slug: "k1freight-web",
    type: "Website",
    tags: ["HTML", "CSS", "JavaScript", "Google Analytics", "Google Charts", "Google Sheets", "Docker", "Nginx", "GCP"],
    description: "Landing for the K1 Freight website including dynamic heatmaps and live stats.",
    link: "https://k1freight.com",
    linkLabel: "Visit Site",
    githubLink: "https://github.com/Kjm520/k1freight-website",
    imageLayout: "landscape",
    images: ["/apps/k1freight-web/imgs/landing.png", "/apps/k1freight-web/imgs/services.png", "/apps/k1freight-web/imgs/heatmap.png"],
  },
  {
    name: "K1 Apps",
    nameLinked: true,
    subtitle: "Project Showcase",
    slug: "k1apps-web",
    type: "Website",
    tags: ["Eleventy", "Nunjucks", "HTML", "CSS", "Google Analytics"],
    description: "This page you are currently on.",
    githubLink: "https://github.com/Kjm520/k1apps-website",
    images: ["/apps/k1apps-web/imgs/landing.png", "/apps/k1apps-web/imgs/privacy.png", "/apps/k1apps-web/imgs/about.png"],
  },
];
